# Generated by Django 5.2.17 on 2026-10-04 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avatar', models.CharField(choices=[('star', 'Estrela'), ('rocket', 'Foguete'), ('leaf', 'Folha'), ('cloud', 'Nuvem')], default='star', max_length=16)),
                ('favorite_color', models.CharField(default='#5B5BD6', max_length=16)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('hearts', models.PositiveSmallIntegerField(default=5)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.schoolyear')),
            ],
            options={
                'ordering': ('nickname',),
            },
        ),
    ]
