# Generated by Django 5.2.17 on 2026-10-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_childprofile'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('used_hint', models.BooleanField(default=False)),
                ('response_time_seconds', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(default='click', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.childprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'Bloqueada'), ('available', 'Disponível'), ('started', 'Iniciada'), ('completed', 'Concluída')], default='locked', max_length=12)),
                ('best_score', models.PositiveSmallIntegerField(default=0)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='accounts.childprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child', 'lesson'), name='one_progress_per_child_lesson')],
            },
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_at', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='accounts.childprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child', 'skill'), name='one_mastery_per_child_skill')],
            },
        ),
    ]
