# Generated by Django 5.2.17 on 2026-10-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('recommended_age', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#5B5BD6', max_length=20)),
                ('icon', models.CharField(default='✦', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='curriculum.schoolyear')),
            ],
            options={
                'ordering': ('school_year__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bncc_code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('thematic_unit', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='curriculum.schoolyear')),
            ],
            options={
                'ordering': ('school_year__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('xp_reward', models.PositiveSmallIntegerField(default=10)),
                ('recommended_exercise_count', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.learningpath')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='curriculum.lesson')),
                ('primary_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='curriculum.skill')),
            ],
            options={
                'ordering': ('path__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('choice', 'Múltipla escolha'), ('count', 'Contagem'), ('compare', 'Maior, menor ou igual'), ('sequence', 'Completar sequência'), ('input', 'Digitar resultado'), ('operation', 'Montar operação'), ('drag', 'Arrastar e soltar'), ('line', 'Reta numérica')], max_length=12)),
                ('prompt', models.TextField()),
                ('short_instruction', models.CharField(max_length=180)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.JSONField()),
                ('explanation', models.TextField()),
                ('hint', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson')),
            ],
            options={
                'ordering': ('lesson__order', 'order'),
                'constraints': [models.UniqueConstraint(fields=('lesson', 'order'), name='unique_exercise_order_per_lesson')],
            },
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('school_year', 'name'), name='unique_path_per_year'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('school_year', 'bncc_code'), name='unique_skill_per_year'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('path', 'order'), name='unique_lesson_order_per_path'),
        ),
    ]
