# Generated by Django 5.2.17 on 2026-10-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_childprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='✦', max_length=30)),
                ('criterion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlocked_by',
            field=models.ManyToManyField(blank=True, through='gamification.AchievementUnlock', to='accounts.childprofile'),
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='accounts.childprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='achievementunlock',
            constraint=models.UniqueConstraint(fields=('achievement', 'child'), name='unique_achievement_unlock'),
        ),
    ]
